name: "Studio PHP SDK"
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    env:
      PY_SDK_STAGING_KEY: ${{ secrets.PHP_SDK_STAGING_KEY }}
      SKYLAB_API_URL: ${{ secrets.SKYLAB_API_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install libvips
        run: sudo apt install libvips-dev --no-install-recommends

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          # extensions: ffi

      - name: Install PHP FFI extension
        run: pecl install ffi

      # - name: Run php ini
      #   run: php --ini

      - name: cat ini
        run: cat /etc/php/8.3/cli/php.ini

      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3

      - name: Update system
        run: sudo apt-get update

      - name: Install dependencies
        run: composer install

      - name: Run phpunit
        run: phpunit tests
